services:
  - type: web
    name: luxhari
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: USER_NAME
        sync: false
      - key: USER_PASSWORD
        sync: false
